name: First Workflow
on: [push]

jobs:
  hello-world:
    name: hello world
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "Hello world !"
  
  todays-date:
    name: Today's date
    runs-on: ubuntu-latest
    steps:
      - name: Print today's date
        run: echo "Today's date is $(date) "

      - name: Check linux os version
        run: cat /etc/os-release* | grep PRETTY_NAME

      - name: Check node version
        run: |
          node --version
          npm --version
  
  

        




